1.0.1

diff --git a/source/RaumserverDaemon/S99raumserver b/source/RaumserverDaemon/S99raumserver
--- a/source/RaumserverDaemon/S99raumserver
+++ b/source/RaumserverDaemon/S99raumserver
@@ -14,6 +14,7 @@ start() {
   
     
     # Check if executable binary is there
+    [ -x $DAEMONPATH$prog ] || echo "Executeable not found"    
     [ -x $DAEMONPATH$prog ] || exit 5    
 
     # wait until network gets available
@@ -28,6 +29,9 @@ start() {
 
         ONLINE=`ifconfig | grep 'Link\|inet' | grep wlan0`
         if [[ ! -z "$ONLINE" ]]; then printf "\nwlan0 online\n"; break; fi
+        
+        ONLINE=`ifconfig | grep 'Link\|inet' | grep uap0`
+        if [[ ! -z "$ONLINE" ]]; then printf "\nuap0 online\n"; break; fi
 
         ONLINE=`ifconfig | grep 'Link\|inet' | grep enp0s3`
         if [[ ! -z "$ONLINE" ]]; then printf "\nenp0s3 online\n"; break; fi
@@ -36,8 +40,8 @@ start() {
     done
   
     # wait a little bit
-    echo "Please be patient. Daemon will start in 3 seconds!"
-    sleep 3  
+    echo "Please be patient. Daemon will start in 20 seconds!"
+    sleep 20 
     
 
     # Check if the daemon is already running. If so write an info to the console and do nothing
@@ -84,5 +88,6 @@ case "$1" in
         echo "Usage: $0 {start|stop|status|restart}"
         exit 2
 esac
+
 
 
